services:

  nginx:
    image: localhost/sitewrangler/nginx
    container_name: sw-nginx
    ports:
    - LOCALIPP:80:80
    - LOCALIPP:443:443
    volumes:
    - SW_BUILD_PATHetc/nginx/conf/:/opt/sitewrangler/usr/nginx/conf/
    - SW_BUILD_PATHetc/nginx/logs/:/opt/sitewrangler/usr/nginx/logs/
    - /seanhome/sitewrangler/dhparam.pem:/etc/ssl/certs/dhparam.pem
    - SW_BUILD_PATHetc/nginx/cache/:/opt/sitewrangler/usr/nginx/cache/
    - /etc/letsencrypt/:/etc/letsencrypt/
    - SW_BUILD_PATHetc/modsec/:/opt/sitewrangler/etc/modsec/
    - /home/:/home/
    restart: always
    command: nginx -g 'daemon off;'
    network_mode: host